server:
  port: 8082

# \u914D\u7F6Emysql\u8FDE\u63A5
spring:
  application:
    name: cloud-provider
  datasource:
    url: jdbc:mysql://localhost:3306/2204?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      #\u6CE8\u518C\u4E2D\u5FC3\u7684\u8BBF\u95EE\u5730\u5740
      defaultZone: http://localhost:8848/eureka/

# \u914D\u7F6Emybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # \u6253\u5370sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # \u5F00\u542Fmybatis\u4E8C\u7EA7\u7F13\u5B58
    cache-enabled: true